[nodes]

[nodes.0]

"lat" = 0.0
"long" = 0.0
"name" = "bleh"

[nodes.1]

"lat" = 0.0
"long" = 0.0
"name" = "bleh"

[nodes.2]

"lat" = 0.0
"long" = 0.0
"name" = "bleh"

[nodes.3]

"lat" = 0.0
"long" = 0.0
"name" = "bleh"